### ISSUE TITLE
Create a GithHub Action to check build errors when pushing code

### ISSUE THREAD

**Issue by JacksonGL** [clueless-interview-web-app/clueless#4]
Resource: https://docs.github.com/en/actions/writing-workflows

Example:
```yml
name: Check Build
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Get yarn cache
        id: yarn-cache
        run: echo "dir=$(yarn cache dir)" >> "$GITHUB_OUTPUT"

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Build packages
        run: |
          yarn install
          yarn build
        working-directory: "."
```
